export const BODY_TYPES = [
  '╨а╨И╨а┬╡╨а╤Ф╨а┬░╨а╨Е', '╨атАе╨бтАж╨бтАЪ╨а┬▒╨а┬╡╨а╤Ъ', '╨атАе╨бтАж╨бтАЪ╨а┬▒╨а┬╡╨а╤Ъ 3 ╨а╤Ф╨а╨Ж.', '╨атАе╨бтАж╨бтАЪ╨а┬▒╨а┬╡╨а╤Ъ 5 ╨а╤Ф╨а╨Ж.', '╨а┬а╨а╤С╨бтАж╨бтАЪ╨а┬▒╨а┬╡╨а╤Ъ', 
  '╨атАЩ╨а╨Е╨а┬╡╨а╤Ф╨а╤Х╨б╨В╨а╤Х╨а┬╢╨а╨Е╨а╤С╨а╤Ъ', '╨атАЩ╨а╨Е╨а┬╡╨а╤Ф╨а╤Х╨б╨В╨а╤Х╨а┬╢╨а╨Е╨а╤С╨а╤Ъ 3 ╨а╤Ф╨а╨Ж.', '╨атАЩ╨а╨Е╨а┬╡╨а╤Ф╨а╤Х╨б╨В╨а╤Х╨а┬╢╨а╨Е╨а╤С╨а╤Ъ 5 ╨а╤Ф╨а╨Ж.', '╨атАУ╨а╨Е╨а╤С╨а╨Ж╨а┬╡╨б╨В╨б╨Г╨а┬░╨а┬╗', 
  '╨а╤Ъ╨б╤У╨а╤Ч╨а┬╡', '╨а╤Ь╨а╤С╨а╨Е╨а╤С╨а╨Ж╨бтАж╨а╨Е', '╨а╤Я╨а╤С╨а╤Ъ╨а┬░╨а╤Ч', '╨а┬а╨а╤С╨а╤Ш╨б╤У╨а┬╖╨а╤С╨а╨Е', '╨атАж╨б╤У╨б╨В╨а┬╢╨а╤Х╨а╨Е', '╨а╤Ъ╨а┬░╨а┬▒╨б╨В╨а╤С╨а╤Х╨а┬╗╨а┬╡╨бтАЪ'
];

export const POPULAR_BRANDS = [
  'Lada (╨атАЩ╨а╤Т╨атАФ)', 'Audi', 'BMW', 'Changan', 'Chery', 'Chevrolet', 'Daewoo', 
  'Ford', 'Geely', 'Haval', 'Honda', 'Hyundai', 'Jaecoo', 'JETOUR', 'Kia', 
  'Land Rover', 'Lexus', 'Mazda', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 
  'Omoda', 'Opel', 'Peugeot', 'Renault', 'Skoda', 'Subaru', 'TENET', 
  'Toyota', 'Volkswagen'
];

export const ALL_BRANDS = [
  'Abarth', 'AC', 'Acura', 'Adam', 'Adler', 'Aito', 'Aiways', 'Aixam', 'Alfa Romeo', 'Alpina', 
  'Alpine', 'AM General', 'Ambertruck', 'AMC', 'Apal', 'Arcfox', 'Ariel', 'Aro', 'Asia', 'Aston Martin', 
  'Auburn', 'Audi', 'Aurus', 'Austin', 'Austin Healey', 'Auto Union', 'Autobianchi', 'Avatr', 'BAIC', 
  'Bajaj', 'Baltijas Dzips', 'Baojun', 'Batmobile', 'BAW', 'Belgee', 'Bentley', 'Bertone', 'Bestune', 
  'Bilenkin', 'Bio Auto', 'Bitter', 'Blaval', 'BMW', 'Borgward', 'Brabus', 'Brilliance', 'Bristol', 
  'Bufori', 'Bugatti', 'Buick', 'BYD', 'Byvin', 'Cadillac', 'Callaway', 'Carbodies', 'Caterham', 'Chana', 
  'Changan', 'Changfeng', 'Changhe', 'Chery', 'Chevrolet', 'Chrysler', 'Ciimo (Dongfeng-Honda)', 
  'Citroen', 'Cizeta', 'Coda', 'Coggiola', 'Cord', 'Cowin', 'Cupra', 'Dacia', 'Dadi', 'Daewoo', 
  'Daihatsu', 'Daimler', 'Dallara', 'Datsun', 'Dayun', 'De Tomaso', 'Deco Rides', 'Delage', 'DeLorean', 
  'Denza', 'Derways', 'DeSoto', 'DKW', 'Dodge', 'Dongfeng', 'Doninvest', 'Donkervoort', 'DR', 'DS', 
  'DW Hower', 'E-Car', 'Eagle', 'Eagle Cars', 'Enovate (Enoreve)', 'Eonyx', 'Everus', 'Evolute', 
  'Excalibur', 'Exeed', 'Facel Vega', 'FAW', 'Ferrari', 'Fiat', 'Fisker', 'Flanker', 'Ford', 'Forthing', 
  'Foton', 'Franklin', 'FSO', 'FSR', 'Fuqi', 'GAC', 'GAC Aion', 'GAC Trumpchi', 'Geely', 'Genesis', 'Geo', 
  'GMA', 'GMC', 'Goggomobil', 'Gonow', 'Gordon', 'GP', 'Great Wall', 'Hafei', 'Haima', 'Hanomag', 
  'Hanteng', 'Haval', 'Hawtai', 'Hedmos', 'Heinkel', 'Hennessey', 'Hindustan', 'HiPhi', 'Hispano-Suiza', 
  'Holden', 'Honda', 'Hongqi', 'Horch', 'Hozon', 'HSV', 'Huaihai (Hoann)', 'HuangHai', 'Huazi', 
  'Hudson', 'Humber', 'Hummer', 'Hycan', 'Hyperion', 'Hyundai', 'iCar', 'iCaur', 'IM Motors (Zhiji)', 
  'Ineos', 'Infiniti', 'Innocenti', 'International Harvester', 'Invicta', 'Iran Khodro', 'Isdera', 
  'Isuzu', 'Iveco', 'JAC', 'Jaecoo', 'Jaguar', 'Jeep', 'Jensen', 'JETOUR', 'Jetta', 'Jiangnan', 'Jidu', 
  'Jinbei', 'JMC', 'JMEV', 'Jonway', 'Kaiyi', 'Karma', 'Kawei', 'KGM', 'Kia', 'Knewstar', 'Koenigsegg', 
  'KTM AG', 'KYC', 'Lada (╨атАЩ╨а╤Т╨атАФ)', 'Lamborghini', 'Lancia', 'Land Rover', 'Landwind', 'Leapmotor', 
  'Letin', 'LEVC', 'Lexus', 'Li Auto (Lixiang)', 'Liebao Motor', 'Lifan', 'Ligier', 'Lincoln', 'Lingxi', 
  'Livan', 'Logem', 'Lotus', 'LTI', 'Lucid', 'Luxeed', 'Luxgen', 'Lynk & Co', 'M-Hero', 'Maextro', 
  'Mahindra', 'Maple', 'Marcos', 'Marlin', 'Marussia', 'Maruti', 'Maserati', 'Matra', 'Maxus', 'Maybach', 
  'Mazda', 'McLaren', 'Mega', 'Mercedes-Benz', 'Mercury', 'Merkur', 'Messerschmitt', 'Metrocab', 'MG', 
  'Micro', 'Microcar', 'Minelli', 'Mini', 'Mitsubishi', 'Mitsuoka', 'Mobilize', 'Morgan', 'Morris', 
  'Nash', 'Nio', 'Nissan', 'Noble', 'Nordcross', 'Oldsmobile', 'Oltcit', 'Omoda', 'Opel', 'Ora', 
  'Orange', 'Osca', 'Oshan', 'Oting', 'Overland', 'Packard', 'Pagani', 'Panoz', 'Perodua', 'Peugeot', 
  'PGO', 'Piaggio', 'Pierce-Arrow', 'Plymouth', 'Polar Stone (Jishi)', 'Polestar', 'Pontiac', 'Porsche', 
  'Premier', 'Proton', 'Puch', 'Puma', 'Punk', 'Qiantu', 'Qingling', 'Qoros', 'Qvale', 'Radar', 
  'Radford', 'Ram', 'Ravon', 'Rayton Fissore', 'Reliant', 'Renaissance', 'Renault', 'Renault Samsung', 
  'Rezvani', 'Rimac', 'Rinspeed', 'Rising Auto', 'Rivian', 'Roewe', 'Rolls-Royce', 'Ronart', 'Rossa', 
  'Rover', 'Rox', 'Saab', 'SAIC', 'Saipa', 'Saleen', 'Sandstorm', 'Santana', 'Saturn', 'Scion', 'Scout', 
  'Sears', 'SEAT', 'Seres', 'Shanghai Maple', 'ShuangHuan', 'Simca', 'Skoda', 'Skywell', 'Skyworth', 
  'Smart', 'Solaris', 'Sollers', 'Soueast', 'Spectre', 'Spyker', 'SsangYong', 'Stelato', 'Steyr', 
  'Studebaker', 'Subaru', 'Suzuki', 'SWM', 'Talbot', 'Tank', 'Tata', 'Tatra', 'Tazzari', 'TENET', 
  'Tesla', 'Thairung', 'Think', 'Tianma', 'Tianye', 'Tofas', 'Toyota', 'Trabant', 'Tramontana', 
  'Triumph', 'TVR', 'Ultima', 'Vauxhall', 'Vector', 'Venturi', 'Venucia', 'VGV', 'VinFast', 'Volga', 
  'Volkswagen', 'Volvo', 'Vortex', 'Voyah', 'VUHL', 'W Motors', 'Wanderer', 'Wartburg', 'Weltmeister', 
  'Westfield', 'Wey', 'Wiesmann', 'Willys', 'Wuling', 'Xcite', 'XEV', 'Xiaomi', 'Xin Kai', 'Xpeng', 
  'Yema', 'Yipai', 'Yudo', 'Yulon', 'Zastava', 'Zeekr', 'Zenos', 'Zenvo', 'Zhido', 'Zibar', 'Zotye', 
  'Zubr', 'ZX', '╨а╤Т╨а╨Ж╨бтАЪ╨а╤Х╨а╤Ф╨а┬░╨а╤Ш', '╨а╤Т╨а╤Ш╨а┬▒╨а┬╡╨б╨В╨а┬░╨а╨Ж╨бтАЪ╨а╤Х', '╨а╤Т╨бтАЪ╨а╤Х╨а╤Ш', '╨атАЬ╨а╤Т╨атАФ', '╨атАФ╨а╤Т╨атАФ', '╨атАФ╨а╨атА║', '╨атАФ╨а╤С╨а╨О', '╨а╨а┬╢', '╨а╤Щ╨а┬░╨а╨Е╨а╤Х╨а╨Е╨а╤С╨б╨В', 
  '╨а╤Щ╨а╤Х╨а╤Ш╨а┬▒╨а┬░╨бтАЪ', '╨атА║╨б╤У╨а╤Т╨атАФ', '╨а╤Ъ╨а╤Х╨б╨Г╨а╤Ф╨а╨Ж╨а╤С╨бтАб', '╨а┬а╨б╤У╨б╨Г╨б╨Г╨а╤Х-╨атАШ╨а┬░╨а┬╗╨бтАЪ', '╨а╨О╨а╤Ъ╨атАФ', '╨а╨О╨а╤Ч╨а╤Х╨б╨В╨бтАЪ╨а╤С╨а╨Ж╨а╨Е╨бтА╣╨а┬╡ ╨а┬░╨а╨Ж╨бтАЪ╨а╤Х ╨а╤С ╨б╨В╨а┬╡╨а╤Ч╨а┬╗╨а╤С╨а╤Ф╨а╤С', 
  '╨а╤Ю╨а┬░╨а╤Ц╨а╤Т╨атАФ', '╨а╨И╨а╤Т╨атАФ', '╨а╨З╨а╨Е╨а╥С╨а┬╡╨а╤Ф╨б╨Г ╨а┬а╨а╤Х╨а╨Ж╨а┬╡╨б╨В', '╨а╨Г-╨а╤Ш╨а╤Х╨а┬▒╨а╤С╨а┬╗╨б╨К'
];
