ALTER TABLE public.offer_items 
ADD COLUMN IF NOT EXISTS weight NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS photo_url TEXT,
ADD COLUMN IF NOT EXISTS delivery_rate NUMERIC DEFAULT 0;

ALTER TABLE public.order_items
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Оригинал';
