-- Таблица чата
CREATE TABLE public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    offer_id BIGINT REFERENCES public.offers(id) ON DELETE SET NULL, -- Может быть NULL, если оффер еще не создан, но чат уже идет (по имени)
    
    sender_role TEXT NOT NULL CHECK (sender_role IN ('ADMIN', 'SUPPLIER')),
    sender_name TEXT NOT NULL, -- Имя поставщика или 'ADMIN'
    
    message TEXT NOT NULL,
    
    -- Опционально: привязка к конкретному товару, если обсуждение идет по позиции
    item_name TEXT, 
    
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Индексы для быстрого поиска сообщений
CREATE INDEX idx_chat_order_supplier ON public.chat_messages(order_id, sender_name);
CREATE INDEX idx_chat_offer ON public.chat_messages(offer_id);

-- Обновление прав (на время разработки)
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for now" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);
