const fs = require('fs');
const path = require('path');

const brandsPath = path.join(__dirname, 'brands.txt');
const sqlPath = path.join(__dirname, 'sql', '29_create_brands_table.sql');

try {
    const brandsData = fs.readFileSync(brandsPath, 'utf8');
    const brands = brandsData.split('\n')
        .map(line => line.trim())
        .filter(line => line.length > 0);

    // Escape single quotes for SQL
    const values = brands.map(brand => `('${brand.replace(/'/g, "''")}')`).join(',\n');

    const sqlContent = `
-- Create Brands Table
CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.brands;
CREATE POLICY "Enable read access for all users" ON public.brands FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.brands;
CREATE POLICY "Enable insert for authenticated users" ON public.brands FOR INSERT WITH CHECK (true);

-- Indexes for fast search
CREATE INDEX IF NOT EXISTS idx_brands_name_trgm ON public.brands USING gin (name gin_trgm_ops);

-- Insert Data
INSERT INTO public.brands (name) VALUES 
${values}
ON CONFLICT (name) DO NOTHING;
`;

    fs.writeFileSync(sqlPath, sqlContent);
    console.log(`Successfully created ${sqlPath} with ${brands.length} brands.`);

} catch (err) {
    console.error('Error:', err);
}
