-- Сначала удаляем старые таблицы (в правильном порядке из-за связей)
DROP TABLE IF EXISTS public.offer_items;
DROP TABLE IF EXISTS public.offers;
DROP TABLE IF EXISTS public.order_items;
DROP TABLE IF EXISTS public.orders;

-- 1. Таблица Заказов (ORDERS)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    client_name TEXT NOT NULL,
    client_phone TEXT,
    
    car_brand TEXT,
    car_model TEXT,
    car_year TEXT,
    vin TEXT,
    
    status_updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    status_admin TEXT DEFAULT 'В обработке',
    status_client TEXT DEFAULT 'В обработке',
    status_supplier TEXT DEFAULT 'Сбор предложений',
    
    location TEXT DEFAULT 'РФ',
    
    visible_to_client BOOLEAN DEFAULT FALSE,
    is_archived BOOLEAN DEFAULT FALSE
);

-- 2. Товары в Заказе (ORDER_ITEMS)
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    
    name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    comment TEXT,
    category TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Предложения от Поставщиков (OFFERS)
CREATE TABLE public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    
    supplier_name TEXT NOT NULL,
    supplier_phone TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT DEFAULT 'Активно'
);

-- 4. Товары в Предложении (OFFER_ITEMS)
CREATE TABLE public.offer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT REFERENCES public.offers(id) ON DELETE CASCADE,
    
    order_item_id BIGINT REFERENCES public.order_items(id),
    
    name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    price NUMERIC NOT NULL,
    currency TEXT DEFAULT 'RUB',
    delivery_days INTEGER,
    
    admin_price NUMERIC,
    admin_currency TEXT,
    is_winner BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Включаем доступ для всех на время разработки)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offer_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for now" ON public.orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for now" ON public.order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for now" ON public.offers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for now" ON public.offer_items FOR ALL USING (true) WITH CHECK (true);
