-- Добавление недостающих колонок в таблицу offer_items

-- 1. Вес и Фото (для Поставщика)
ALTER TABLE public.offer_items 
ADD COLUMN IF NOT EXISTS weight NUMERIC DEFAULT 0;

ALTER TABLE public.offer_items 
ADD COLUMN IF NOT EXISTS photo_url TEXT;

-- 2. Комментарий админа и Тариф доставки (для Админа)
ALTER TABLE public.offer_items 
ADD COLUMN IF NOT EXISTS admin_comment TEXT;

ALTER TABLE public.offer_items 
ADD COLUMN IF NOT EXISTS delivery_rate NUMERIC DEFAULT 0;

-- 3. Комментарий поставщика (НОВОЕ)
ALTER TABLE public.offer_items 
ADD COLUMN IF NOT EXISTS comment TEXT;

-- 4. Таблица ЧАТА (НОВОЕ)
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    offer_id BIGINT REFERENCES public.offers(id) ON DELETE SET NULL, 
    sender_role TEXT NOT NULL CHECK (sender_role IN ('ADMIN', 'SUPPLIER')),
    sender_name TEXT NOT NULL, 
    message TEXT NOT NULL,
    item_name TEXT, 
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_order_supplier ON public.chat_messages(order_id, sender_name);
CREATE INDEX IF NOT EXISTS idx_chat_offer ON public.chat_messages(offer_id);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for now" ON public.chat_messages;
CREATE POLICY "Enable all access for now" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);
